spring.application.name=backend
spring.datasource.url=jdbc:h2:file:./data/queuemaster_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=queuemasters
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true